notifications:
  email: false
dist: trusty
sudo: false
addons:
  apt:
    packages:
      - python-numpy
before_install:
  - "pyenv install 3.4.0"
  - "pyenv global 3.4.0"
language: java
jdk:
  - oraclejdk8
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
