notifications:
  email: false
dist: trusty
sudo: false
addons:
  apt:
    packages:
    - python-numpy
language: java
jdk:
- oraclejdk8
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
    secure: MqdS7cKqG6JvaRk8M+Bu5jdcUpPMQQUjQkrc9wMRfVVqd31Rfameh2NSUPaxWG/ATwRFIVVZ331hjeaAP51ixDK6ltQdHeGFW2Uj2vA0TYJWdCrkoeng9KAISLxqLWD1gmJaXlOQwjEZr8pRYjQgWOe/haKkTl0M7ebjbSmGBUKP8J+otnEBocLNgMmA2lhvJalSjiy5HtN+TA01oMDR1hzkikkI10YxaP3rv0OWKXvcVUHtg9pui+ohcmm92tOhVaRJo5s9kNj7abfTk6u1E17dcErtE+MHV6Bm+n5PRmQdXB6NebYjB1L9FF453yHBzTX/y1FI+CXASdtLm7VAXMQktZgPbPg4ODSWVMqJalQhuFqtGATB+fuNePgLiPSxtxhM4XYKg4dshP1SKgQBPgQRFCxxxLZqAvdeDeNw0eXKhvKELGtgKfrFrCffxP54s54qgus1z5Ctqtb8hmbn0ye0Zr6YMv4NdqkHGHK/sGujiJcAJHaOWKxUhlcrHXJNuS1S+XHsC46X6tWgS5XdwJ2vhVFmc0nIlhoFH5hQFLz37jI3SWQoh97Ut5Q2BVYvpSAq2NjHPqdC5z5+sJgaT8WWuQyNI2/N8IdgoxlqEAg8pbxaMupyXuve/HKyESXjtiCU7ugyOPe14y1uX4ZUnwN1MYz2uL7fW5+eo+8FASY=
after_success:
- ./publish_javadoc.sh
