dist: trusty
sudo: false
language: java
jdk:
  - oraclejdk8
before_script:
  - "pyenv install 3.4.0"
  - "pyenv activate 3.4.0"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
