//Source file generated by Etomica

package etomica.simulations;
import etomica.*;

public class _3DOrientatedSphere extends Simulation {

  public _3DOrientatedSphere() {
    super(new etomica.Space3D());
    Simulation.instance = this;
    etomica.IntegratorHard integratorHard0  = new etomica.IntegratorHard();
    etomica.Controller controller0  = new etomica.Controller();
    etomica.PotentialHardSphere potentialHardSphere2  = new etomica.PotentialHardSphere();
      potentialHardSphere2.setCollisionDiameter(5.0);
    etomica.Phase phase0  = new etomica.Phase();
    phase0.setConfiguration(new ConfigurationFcc());
    etomica.DisplayPhase displayPhase0  = new etomica.DisplayPhase();
    etomica.SpeciesSpheresRotating speciesSpheresRotating0  = new etomica.SpeciesSpheresRotating();
      speciesSpheresRotating0.setDiameter(5.0);
      speciesSpheresRotating0.setNMolecules(108);
      speciesSpheresRotating0.setColor(new java.awt.Color(0,255,255));
    etomica.P2SimpleWrapper potentialHardSphere3  = new etomica.P2SimpleWrapper(potentialHardSphere2);
  } //end of constructor

  public static void main(String[] args) {
    javax.swing.JFrame f = new javax.swing.JFrame();
    f.setSize(600,350);

    Simulation sim = new _3DOrientatedSphere();
    sim.mediator().go(); 
    f.getContentPane().add(sim.panel());

    f.pack();
    f.show();
    f.addWindowListener(new java.awt.event.WindowAdapter() {
        public void windowClosing(java.awt.event.WindowEvent e) {System.exit(0);}
    });
  }//end of main
}//end of class
