//Source file generated by Etomica

package etomica.simulations;

import etomica.*;

public class HSMD3DWithDefectAndWall extends Simulation {

  public HSMD3DWithDefectAndWall() {
    super(new etomica.Space3D());
    Simulation.instance = this;
    etomica.PotentialHardSphere potentialHardSphere2  = new etomica.PotentialHardSphere();
    etomica.PotentialHardSphere potentialHardSphere4  = new etomica.PotentialHardSphere();
    etomica.SpeciesSpheres speciesSpheres2  = new etomica.SpeciesSpheres();
      speciesSpheres2.setColor(new java.awt.Color(255,0,255));
      speciesSpheres2.setNMolecules(1);
    etomica.DisplayPhase displayPhase0  = new etomica.DisplayPhase();
    etomica.PotentialHardSphereWall potentialHardSphereWall8  = new etomica.PotentialHardSphereWall();
    etomica.IntegratorHard integratorHard0  = new etomica.IntegratorHard();
    etomica.SpeciesSpheres speciesSpheres1  = new etomica.SpeciesSpheres();
      speciesSpheres1.setColor(new java.awt.Color(0,255,0));
      speciesSpheres1.setNMolecules(31);
    etomica.SpeciesWalls speciesWalls0  = new etomica.SpeciesWalls();
      speciesWalls0.setColor(new java.awt.Color(0,0,255));
    etomica.PotentialHardSphere potentialHardSphere0  = new etomica.PotentialHardSphere();
    etomica.PotentialHardSphereWall potentialHardSphereWall6  = new etomica.PotentialHardSphereWall();
    etomica.Controller controller0  = new etomica.Controller();
    etomica.Phase phase0  = new etomica.Phase();
    etomica.P2SimpleWrapper potentialHardSphere5  = new etomica.P2SimpleWrapper(potentialHardSphere4);
    etomica.P2SimpleWrapper potentialHardSphere1  = new etomica.P2SimpleWrapper(potentialHardSphere0);
    etomica.P2SimpleWrapper potentialHardSphereWall7  = new etomica.P2SimpleWrapper(potentialHardSphereWall6);
    etomica.P2SimpleWrapper potentialHardSphereWall9  = new etomica.P2SimpleWrapper(potentialHardSphereWall8);
    etomica.P2SimpleWrapper potentialHardSphere3  = new etomica.P2SimpleWrapper(potentialHardSphere2);
  } //end of constructor

  public static void main(String[] args) {
    javax.swing.JFrame f = new javax.swing.JFrame();
    f.setSize(600,350);

    Simulation sim = new HSMD3DWithDefectAndWall();
    sim.mediator().go(); 
    f.getContentPane().add(sim.panel());

    f.pack();
    f.show();
    f.addWindowListener(new java.awt.event.WindowAdapter() {
        public void windowClosing(java.awt.event.WindowEvent e) {System.exit(0);}
    });
  }//end of main
}//end of class
