package simulate.gui;

import java.awt.*;
import javax.swing.*;

/**
 * A basic implementation of the JDialog class.
 */
public class JAboutDialog extends javax.swing.JDialog {
	// Used for addNotify check.
	boolean fComponentsAdjusted = false;

	//{{DECLARE_CONTROLS
	javax.swing.JButton okButton = new javax.swing.JButton();
	javax.swing.JLabel aboutLabel1 = new javax.swing.JLabel();
	javax.swing.JLabel aboutLabel2 = new javax.swing.JLabel();
	javax.swing.JLabel aboutLabel3 = new javax.swing.JLabel();
	javax.swing.JLabel aboutLabel4 = new javax.swing.JLabel();
	javax.swing.JLabel aboutLabel5 = new javax.swing.JLabel();
	java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
	java.awt.GridBagLayout gbl = new java.awt.GridBagLayout();
	//}}
	
	public JAboutDialog(Frame parentFrame) {
		super(parentFrame);
		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
		//{{INIT_CONTROLS
		setTitle("Etomica Molecular Simulation Environment");
		setModal(true);
		getContentPane().setLayout(gbl);
		setSize(350,200);
		setVisible(false);
		
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbl.setConstraints(aboutLabel1, gbc);
		aboutLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		aboutLabel1.setFont(new Font("Bold", Font.BOLD, 14));
		aboutLabel1.setText("The Etomica Molecular Simulation Environment");
		getContentPane().add(aboutLabel1);
    	gbc.gridy = 1;
		gbl.setConstraints(aboutLabel2, gbc);
		aboutLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		aboutLabel2.setText("Written by Bryan C. Mihalick");
		getContentPane().add(aboutLabel2);
		gbc.gridy = 2;
		gbl.setConstraints(aboutLabel4, gbc);
		aboutLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		aboutLabel4.setText("University at Buffalo");
		getContentPane().add(aboutLabel4);
		gbc.gridy = 3;
		gbl.setConstraints(aboutLabel5, gbc);
		aboutLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		aboutLabel5.setText("Buffalo, NY 14226");
		getContentPane().add(aboutLabel5);
		gbc.gridy = 4;
		gbl.setConstraints(okButton, gbc);
		okButton.setText("OK");
		okButton.setActionCommand("OK");
		okButton.setOpaque(false);
		okButton.setMnemonic((int)'O');
		getContentPane().add(okButton);
		okButton.setBounds(124,137,51,25);
		//}}

		//{{REGISTER_LISTENERS
		SymWindow aSymWindow = new SymWindow();
		this.addWindowListener(aSymWindow);
		SymAction lSymAction = new SymAction();
		okButton.addActionListener(lSymAction);
		//}}
	}

	public void setVisible(boolean b){
	    if (b){
    		Rectangle bounds = (getParent()).getBounds();
    		Dimension size = getSize();
    		setLocation(bounds.x + (bounds.width - size.width)/2,
    			        bounds.y + (bounds.height - size.height)/2);
	    }

		super.setVisible(b);
	}

	public void addNotify(){
		// Record the size of the window prior to calling parents addNotify.
		Dimension d = getSize();

		super.addNotify();

		if (fComponentsAdjusted)
			return;
		// Adjust components according to the insets
		Insets insets = getInsets();
		setSize(insets.left + insets.right + d.width, insets.top + insets.bottom + d.height);
		Component components[] = getContentPane().getComponents();
		for (int i = 0; i < components.length; i++){
			Point p = components[i].getLocation();
			p.translate(insets.left, insets.top);
			components[i].setLocation(p);
		}
		fComponentsAdjusted = true;
	}


	class SymWindow extends java.awt.event.WindowAdapter{
		
		public void windowClosing(java.awt.event.WindowEvent event){
			Object object = event.getSource();
			if (object == JAboutDialog.this)
				jAboutDialog_windowClosing(event);
		}
	}

	void jAboutDialog_windowClosing(java.awt.event.WindowEvent event){
		// to do: code goes here.
			 
		jAboutDialog_windowClosing_Interaction1(event);
	}

	void jAboutDialog_windowClosing_Interaction1(java.awt.event.WindowEvent event) {
		try {
			// JAboutDialog Hide the JAboutDialog
			this.setVisible(false);
		} catch (Exception e) {}
	}
	
	class SymAction implements java.awt.event.ActionListener{
		
		public void actionPerformed(java.awt.event.ActionEvent event){
			Object object = event.getSource();
			if (object == okButton)
				okButton_actionPerformed(event);
		}
	}

	void okButton_actionPerformed(java.awt.event.ActionEvent event){
		// to do: code goes here.
			 
		okButton_actionPerformed_Interaction1(event);
	}

	void okButton_actionPerformed_Interaction1(java.awt.event.ActionEvent event) {
		try {
			// JAboutDialog Hide the JAboutDialog
			this.setVisible(false);
		} catch (Exception e) {}
	}
}