package etomica;

/** 
 * Class used to define an action on an AtomPair.
 * Can be passed to allPairs method of an AtomPair iterator to perform the action on 
 * all pairs generated by the iterator
 */
public abstract class AtomPairAction implements AtomPairActive, java.io.Serializable {
	public final AtomPairActive.InnerWrapper wrapper;
	public final AtomPairActive.OuterWrapper outerWrapper;
	public AtomPairAction(Space space) {
		wrapper = new AtomPairActive.InnerWrapper(this, new AtomPair(space));
		outerWrapper = new AtomPairActive.OuterWrapper(this);
	}
	
    /**
	 * @see etomica.AtomPairActive#actionPerformed(etomica.AtomPair)
	 */
	public abstract void actionPerformed(AtomPair pair);
    
	/**
	 * @see etomica.AtomPairActive#innerWrapper()
	 */
	public final AtomPairActive.InnerWrapper innerWrapper() {return wrapper;}
	/**
	 * @see etomica.AtomPairActive#outerWrapper()
	 */
	public final AtomPairActive.OuterWrapper outerWrapper() {return outerWrapper;}

}//end of AtomPairAction
