package etomica;
import java.awt.event.*;

/**
 * A PhaseEvent that is generated by some input (mouse or key) action on a DisplayPhase object.
 * Extends PhaseEvent while adding keyEvent and mouseEvent objects that can be used
 * to determine exactly what input events generated the phase event.
 *
 * @see PhaseEvent
 * @see DisplayPhase
 * @see DisplayPhaseListener
 */
public class DisplayPhaseEvent extends PhaseEvent {
    
    public DisplayPhaseEvent(Object source) {
        super(source);
    }
    
    public KeyEvent getKeyEvent() {return keyEvent;}
    public void setKeyEvent(KeyEvent evt) {keyEvent = evt;}
    public MouseEvent getMouseEvent() {return mouseEvent;}
    public void setMouseEvent(MouseEvent evt) {mouseEvent = evt;}
    
    protected KeyEvent keyEvent = null;
    protected MouseEvent mouseEvent = null;
    
}//end of DisplayPhaseEvent
