/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

package etomica.normalmode;

import etomica.space.Vector;
import etomica.box.Box;

/**
 * Interface for a class the returns the appropriate wave vectors for a box
 * and primitive
 *
 * @author Andrew Schultz
 */
public interface WaveVectorFactory {

    /**
     * Tells the instance to make wave vectors appropriate for the given box. 
     * The wave vectors will not include the 0 vector, any two  vectors which 
     * are opposites or any wave vector that is redundant with another.
     */
    public void makeWaveVectors(Box box);
    
    /**
     * Returns the wave vectors generated by makeWaveVectors
     */
    public Vector[] getWaveVectors();

    /**
     * Returns the coefficients for the wave vectors returned by 
     * getWaveVectors.  If two of the wave vectors are redundant, their 
     * coefficient will be 0.5.  Others will have a coefficient of 1.0.
     */
    public double[] getCoefficients();

}
